<?php
/**
 * ./vendor/magento/module-sales/view/frontend/templates/order/info/buttons.phtml
 */
?>
<div class="actions">
    <?php  $_order = $block->getOrder() ?>
    <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId())) : ?>
        <a href="#" data-post='<?php /* @escapeNotVerified */ echo
        $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
            ->getPostData($block->getReorderUrl($_order))
        ?>' class="action order">
            <span><?= /* @escapeNotVerified */ __('Reorder') ?></span>
        </a>
    <?php endif ?>
    <?php if ($this->canPaymentPage($_order)) : ?>
    <a 
        href="<?= /* @escapeNotVerified */ $block->getPaymentUrl($_order) ?>"
        class="action order">
            <span><?= /* @escapeNotVerified */ __('Payment page') ?></span>
    </a>
    <?php endif ?>
    <a class="action print"
       href="<?= /* @escapeNotVerified */ $block->getPrintUrl($_order) ?>"
       onclick="this.target='_blank';">
        <span><?= /* @escapeNotVerified */ __('Print Order') ?></span>
    </a>
    <?= $block->getChildHtml() ?>
</div>
